spring:
  application:
    name: zipkin
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
server:
  port: 18081

micrometer:
  tracing:
    exporter:
      zipkin:
        sender:
          max-queued-spans: 0
          batch-size: 5
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    com.acorn.zipkin: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    org.springframework.cloud.sleuth.zipkin2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http: TRACE
    io.zipkin: DEBUG
    io.micrometer: DEBUG
    io.zipkin.reporter2: DEBUG
    io.micrometer.tracing: DEBUG
